### ISSUE TITLE
Consider reducing the log level of `successfully renewed lease` to DEBUG

### ISSUE THREAD

**Issue by jbg** [hendrikmaus/kube-leader-election#34]
On some of our less-busy controllers 90+% of the log output is from [this](https://github.com/hendrikmaus/kube-leader-election/blob/master/src/lease.rs#L91). I think in most cases normal operation should be silent and deviations should be called out in logs, so it would make sense to reduce the severity of this to DEBUG. What do you think?

**Comment by hendrikmaus** [comment]
Absolutely, would you mind creating a pull-request? I'll release asap afterwards. 

BTW, are any of your controllers open-source and we could link to them from this project?

**Comment by jbg** [comment]
> Absolutely, would you mind creating a pull-request? I'll release asap afterwards.

Created #36. I left the other similar log messages at INFO ("successfully acquired lease", "lease is held by X and has not expired") on the basis that they are much lower frequency and indicate state changes rather than just steady state so are more useful.

> BTW, are any of your controllers open-source and we could link to them from this project?

Not yet, but at least a couple are planned to be open-sourced, and when they are I'll let you know!
